on: [pull_request]

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Post a comment with run id
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Action add comment with vars
        uses: ./
        with:
          comment: 'Current build $GITHUB_RUN_ID has passed ✅'

      - name: Action add comment
        uses: ./
        with:
          comment: 'Plain *comment* `message` :rocket:'
